export const APP_CONSTANTS = {
    BRAVO_DATA: "BRAVO_DATA",
    BRAVO_LIST: "BRAVO_LIST",
    ALPHA_DATA: "ALPHA_DATA",
    CHARLIE_DATA: "CHARLIE_DATA",
    IS_PURCHASED_FULL_VERSION: "IS_PURCHASED_FULL_VERSION",
    ALPHA_SCORE: "ALPHA_SCORE",
    CHARLIE_SCORE: "CHARLIE_SCORE",
    IS_UPDATES_AVAIALBLE: "IS_UPDATES_AVAIALBLE",
    NOTIFICATION_TIME: "NOTIFICATION_TIME",
    IS_NOTIFICATION_CHECKED: "IS_NOTIFICATION_CHECKED",
};